name: Build and Deploy DeSimone Web App

on:
  push:
    branches: [ "main", "dev" ]
  workflow_dispatch:
  
env:
  AZURE_WEBAPP_NAME: "app-desimone-web-eastus-dev"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Install dependencies
        run: dotnet restore ./src/Presentation

      - name: Build with dotnet
        run: dotnet build ./src/Presentation --configuration Release --no-restore

      - name: dotnet publish
        run: dotnet publish ./src/Presentation --configuration Release --no-build -o ./publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.DESIMONE_PUBLISH_SECRET }}
          package: ./publish